data_preprocessing:
  audio_slice_duration_ms: 1000
  sample_rate: 14000
feature_extraction:
  window_len: 1024
  window_stride: 512
  window_scaling_bits: 12
  mel_n_channels: 25
  mel_low_hz: 4000
  mel_high_hz: 6750
  mel_post_scaling_bits: 6
model_training:
  seed: 42
  n_epochs: 20
  shuffle_buff_n: 10000
  batch_size: 128
  early_stopping:
    patience: 0
embedded_code_generation:
  serial_device: "/dev/ttyUSB0" # Replace with your serial device